`timescale 1ns / 1ps

// Integration test: weight_fifo directly driving mmu's weight-loading
// ports. Reproduces the exact scenario from mmu_tb.sv Test 1 + Test 2
// (W = [[4,5],[2,3]], A = [[1,2],[3,4]] -> C = [[8,11],[20,27]]), but
// instead of the testbench hand-driving in_col_0/in_col_1/capture_weight,
// those signals are generated by weight_fifo. This is the proof that
// weight_fifo's out_col_*_valid can be wired straight into
// capture_weight_col_* with no extra glue logic, as designed.
module weight_fifo_mmu_integration_tb;
    localparam int WEIGHT_WIDTH = 8;
    localparam int FIFO_DEPTH   = 4;

    logic clk;
    logic reset;

    // weight_fifo <-> mmu glue
    logic loading_phase;
    logic signed [WEIGHT_WIDTH-1:0] wf_col_0, wf_col_1;
    logic wf_col_0_valid, wf_col_1_valid;

    // off-chip write port
    logic write_enable_col_0, write_enable_col_1;
    logic signed [WEIGHT_WIDTH-1:0] write_data_col_0, write_data_col_1;
    logic swap_banks;
    logic shadow_loaded, active_bank, active_empty, active_full, any_shadow_full;

    // mmu activation/output side
    logic signed [7:0] in_row_0, in_row_1;
    logic in_row_0_valid, in_row_1_valid;
    logic signed [15:0] out_partial_sum_0, out_partial_sum_1;
    logic out_partial_sum_0_valid, out_partial_sum_1_valid;

    int errors = 0;
    int exp_col0_q[$], exp_col1_q[$];

    weight_fifo #(
        .WEIGHT_WIDTH(WEIGHT_WIDTH),
        .FIFO_DEPTH(FIFO_DEPTH)
    ) u_wf (
        .clk(clk),
        .reset(reset),
        .write_enable_col_0(write_enable_col_0),
        .write_data_col_0(write_data_col_0),
        .write_enable_col_1(write_enable_col_1),
        .write_data_col_1(write_data_col_1),
        .swap_banks(swap_banks),
        .shadow_loaded(shadow_loaded),
        .active_bank(active_bank),
        .loading_phase(loading_phase),
        .out_col_0(wf_col_0),
        .out_col_0_valid(wf_col_0_valid),
        .out_col_1(wf_col_1),
        .out_col_1_valid(wf_col_1_valid),
        .active_empty(active_empty),
        .active_full(active_full),
        .any_shadow_full(any_shadow_full)
    );

    mmu u_mmu (
        .clk(clk),
        .reset(reset),
        .loading_phase(loading_phase),
        .capture_weight_col_0(wf_col_0_valid),
        .capture_weight_col_1(wf_col_1_valid),
        .in_row_0(in_row_0),
        .in_row_0_valid(in_row_0_valid),
        .in_row_1(in_row_1),
        .in_row_1_valid(in_row_1_valid),
        .in_col_0(wf_col_0),
        .in_col_0_valid(wf_col_0_valid),
        .in_col_1(wf_col_1),
        .in_col_1_valid(wf_col_1_valid),
        .out_partial_sum_0(out_partial_sum_0),
        .out_partial_sum_0_valid(out_partial_sum_0_valid),
        .out_partial_sum_1(out_partial_sum_1),
        .out_partial_sum_1_valid(out_partial_sum_1_valid)
    );

    always #5 clk = ~clk;

    always @(posedge clk) begin
        if (!reset) begin
            if (out_partial_sum_0_valid) begin
                if (exp_col0_q.size() == 0) begin
                    $error("[FAIL] Unexpected col0 output %0d at time %0t", out_partial_sum_0, $time);
                    errors++;
                end else begin
                    int e;
                    e = exp_col0_q.pop_front();
                    if (out_partial_sum_0 !== e) begin
                        $error("[FAIL] col0 at %0t: got %0d, expected %0d", $time, out_partial_sum_0, e);
                        errors++;
                    end else begin
                        $display("[PASS] col0 at %0t: %0d", $time, out_partial_sum_0);
                    end
                end
            end
            if (out_partial_sum_1_valid) begin
                if (exp_col1_q.size() == 0) begin
                    $error("[FAIL] Unexpected col1 output %0d at time %0t", out_partial_sum_1, $time);
                    errors++;
                end else begin
                    int e;
                    e = exp_col1_q.pop_front();
                    if (out_partial_sum_1 !== e) begin
                        $error("[FAIL] col1 at %0t: got %0d, expected %0d", $time, out_partial_sum_1, e);
                        errors++;
                    end else begin
                        $display("[PASS] col1 at %0t: %0d", $time, out_partial_sum_1);
                    end
                end
            end
        end
    end

    initial begin
        clk = 0;
        reset = 1;
        loading_phase = 0;
        write_enable_col_0 = 0; write_data_col_0 = 0;
        write_enable_col_1 = 0; write_data_col_1 = 0;
        swap_banks = 0;
        in_row_0 = 0; in_row_0_valid = 0;
        in_row_1 = 0; in_row_1_valid = 0;

        #15;
        @(posedge clk);
        #1 reset = 0;

        $display("\n=== Starting weight_fifo + mmu Integration Testbench ===\n");

        // C1 = A1 @ W1 = [[8,11],[20,27]]
        exp_col0_q.push_back(8);  exp_col1_q.push_back(11);
        exp_col0_q.push_back(20); exp_col1_q.push_back(27);

        // Load W1 = [[4,5],[2,3]] into shadow bank (bank1, since bank0
        // is active-by-default-but-empty), then swap it in.
        // Enqueue bottom row first (2,3), then top row (4,5).
        $display("\n Test 1: DMA-style write into shadow bank");
        @(posedge clk);
        #1;
        write_enable_col_0 = 1; write_data_col_0 = 8'sd2;
        write_enable_col_1 = 1; write_data_col_1 = 8'sd3;
        @(posedge clk);
        #1;
        write_data_col_0 = 8'sd4;
        write_data_col_1 = 8'sd5;
        @(posedge clk);
        #1;
        write_enable_col_0 = 0; write_data_col_0 = 0;
        write_enable_col_1 = 0; write_data_col_1 = 0;

        if (!shadow_loaded) begin
            $error("[FAIL] shadow_loaded should be 1 after 2 writes/col");
            errors++;
        end

        $display("\n Test 2: swap shadow -> active, then drain into MMU via loading_phase");
        @(posedge clk);
        #1;
        swap_banks = 1;
        @(posedge clk);
        #1;
        swap_banks = 0;
        loading_phase = 1;   // weight_fifo now drains active bank into mmu automatically

        // Hold loading_phase high for 3 cycles (fifo has 2 entries/col);
        // weight_fifo's out_col_*_valid will deassert on its own once drained.
        @(posedge clk);
        #1;
        @(posedge clk);
        #1;
        @(posedge clk);
        #1;
        loading_phase = 0;

        @(posedge clk); // idle settle tick, matches mmu_tb.sv pattern

        // Test 3: stream activations A = [[1,2],[3,4]], identical to
        // mmu_tb.sv Test 2.
        $display("\n Test 3: Systolic Activation Streaming");
        @(posedge clk);
        #1;
        in_row_0 = 8'sd1; in_row_0_valid = 1'b1;
        in_row_1 = 8'sd0; in_row_1_valid = 1'b0;

        @(posedge clk);
        #1;
        in_row_0 = 8'sd3; in_row_0_valid = 1'b1;
        in_row_1 = 8'sd2; in_row_1_valid = 1'b1;

        @(posedge clk);
        #1;
        in_row_0 = 8'sd0; in_row_0_valid = 1'b0;
        in_row_1 = 8'sd4; in_row_1_valid = 1'b1;

        @(posedge clk);
        #1;
        in_row_0 = 8'sd0; in_row_0_valid = 1'b0;
        in_row_1 = 8'sd0; in_row_1_valid = 1'b0;

        #40;

        $display("\n=== SIMULATION COMPLETE ===\n");
        if (errors == 0 && exp_col0_q.size() == 0 && exp_col1_q.size() == 0) begin
            $display(">>> ALL weight_fifo + mmu INTEGRATION TESTS PASSED <<<");
        end else begin
            $display(">>> %0d FAILURE(S), %0d expected output(s) never arrived <<<",
                      errors, exp_col0_q.size() + exp_col1_q.size());
        end

        $finish;
    end

    initial begin
        $dumpfile("weight_fifo_mmu_integration.vcd");
        $dumpvars(0, weight_fifo_mmu_integration_tb);
    end
endmodule
